### ISSUE TITLE
decomposer empty tank not working

### ISSUE THREAD

**Issue by StrangeThistle** [jakimfett/Minechem#582]
I've updated to build 369 in the Material Energy^4 pack (SSP). I've set up to pump drums of chemicals into a row of 6 decomposers & usually have a little left in the internal tanks at the end of the cycle (~50-150mb). When I hit the "empty tank" button, the tank shows as empty but will not accept a different chemical. If I re-log, the residue shows back up in the tank. Breaking & replacing the decomposer fixes the problem for the next chemical.

If it helps, this feels like a de-syncing issue. I do experience some other de-syncing problems in this pack, usually block-lag trying to break certain blocks with certain tools (ender io conduits with a pickaxe, for example).

**Comment by jakimfett** [comment]
@StrangeThistle could I get you to test this in the [latest build](http://jenkins.jakimfett.com/view/ForgeModding/job/Minechem%201.7%20v5/)?

**Comment by StrangeThistle** [comment]
I’m afraid there is no apparent change in behavior from 369 to 374. The dump fluid button will visually empty the tank client side, but will not functionally empty the tank in single player.

While I’m at it, the chemist’s journal still won’t set the active recipe in the synthesizer. I don’t know if there is an open thingy for this, but it did come up on the FTB ME4 discussion a while back.

The discussion of minechem’s shortcomings seems to have been sidelined by the discussion about just how broken the Fluxed Crystals mod is at the moment. I just hope we don’t break a fledgling mod author in the process. The internet is not always a kind place to live.
 
On Feb 1, 2015, at 11:32 PM, jakimfett <notifications@github.com> wrote:

@StrangeThistle <https://github.com/StrangeThistle> could I get you to test this in the latest build <http://jenkins.jakimfett.com/view/ForgeModding/job/Minechem%201.7%20v5/>?

**Comment by hilburn** [comment]
The chemist's journal definitely does set recipes in the synthesiser - just ask DW20, who spent a good 5 minutes in his ME4 LP resetting his recipe a half dozen times by accident.
Both times I have looked for any issues in the synthesiser recipe setting I have found no issues, so if you could provide concrete examples, that don't work I'd appreciate it.
I will check the purge issues though, that's worrysome

**Comment by StrangeThistle** [comment]
Before anyone asks, both problems seem to persist in build 375. I will go ahead & open a separate issue for the journal.

**Comment by jakimfett** [comment]
@StrangeThistle let's keep this focused on the fluid container dump issue. If you're certain the chemistry journal has a bug, please review the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting) and then open a new ticket for that issue.

Could I get you to test the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem 1.7 v5/), please? @hilburn pushed a fix to the 1.7.10 v5 code that should fix it, but I'd like confirmation from you that it's working.

**Comment by StrangeThistle** [comment]
OK, I've set up an instance in MultiMC with only minechem & enderIO, & the fix seems to be working fine. I'll have to break & replace or set up new equipment in my ME4 game to double check in that environment.

**Comment by jakimfett** [comment]
Awesome, I'm going to close this issue. If it shows up again with the latest builds, go ahead and open a new ticket.

**Comment by way2muchnoise** [comment]
@StrangeThistle Also it could be that the MT (tweaked) recipes are derping out the book tho

**Comment by StrangeThistle** [comment]
Still can't get the dump fluid button to work properly in the ME4 pack, so it is probably some other mod making things a little wonky in general. I'm willing to give up & live with the way it is currently working at this point.

**Comment by hilburn** [comment]
well.. i've checked it on MP and SP and it works fine in dev - and works in ME\^4 for me when i compiled and loaded it, so I'm not sure what to say about that. If you are running on a server then it's possible some weirdness is going on but otherwise i have no clue

**Comment by jakimfett** [comment]
@StrangeThistle the version in ME^4 doesn't have the fix yet, you'll need to ask @parcel31u to update it.

**Comment by StrangeThistle** [comment]
If the fix is self contained in build 375, you'd think it would be working, as I've updated minechem manually to test. If it involves changes to configs, jsons, or any other mod, then I should have to wait for a pack update as I haven't changed anything else.

Anyway, I am playing (straight single player, no server set up) on an older laptop at an fps that many people with better computers consider unplayable. Even minor potential desync issues may be exaggerated for me.

**Comment by jakimfett** [comment]
Odd...I'll see if I can reproduce this in the ME^4 pack if I've got time later today.

**Comment by StrangeThistle** [comment]
Very odd. I just added minechem to the cut-down, bastardized version of the DW20 pack I usually play, & the dump fluid button works just fine for me there. Yesterday I even started a new ME^4 game & changed the testing set-up around a bit to make sure there wasn't some sort of artifact in my save interfering. You seem to have found something to fix, so it wasn't just a rare thing that only happens to my particular combination of OS, java, & hardware. If it is not being weird for anyone else at this point, the only thing left to me to try is to copy my save & do a fresh install of the pack.
